<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Agenda</title>
	<link href="<?php echo $this->baseUrl() . '/css/bootstrap.css'; ?>" media="all" rel="stylesheet" type="text/css" />
	<script src="https://code.jquery.com/jquery-1.12.4.js"integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=" crossorigin="anonymous"></script>
	<!-- 	<script src="<?php echo $this->baseUrl() . '/js/jquery-3.1.1.min.js'; ?>" type="text/javascript"></script> -->
	<link href="<?php echo $this->baseUrl() . '/css/datatable_boostrap.css'; ?>" media="all" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css"/>
	<link href="<?php echo $this->baseUrl() . '/css/select2.css'; ?>" media="all" rel="stylesheet" type="text/css" />
	<script src="<?php echo $this->baseUrl() . '/js/bootstrap.js'; ?>" type="text/javascript"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl() . '/js/dist/jquery.validate.js'; ?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl() . '/js/select2/select2.full.js'; ?>" type="text/javascript"></script>
</head>
<body>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Agenda</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
				<li><a href="../navbar-static-top/">Static top</a></li>
				<li><a href="../navbar-fixed-top/">Fixed top</a></li>
			</ul>
		</div><!--/.nav-collapse -->
	</div><!--/.container-fluid -->
</nav>
<div class="container">
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-7">
			<button type="button" class="btn btn-warning pull-right" data-toggle="modal" data-target="#myModal">Nuevo Contacto</button>
		</div>
		<div class="col-md-1"></div>
	</div>
	<div class="col-md-1"></div>
	<div class="row">
		<div class="col-md-10 table-render">
			<br/>
			<table class="table table-striped table-bordered">
				<thead>
				<tr>
					<th>Nombre</th>
					<th>Apellido</th>
					<th>Dirección</th>
					<th>Correo</th>
					<th>Telefono</th>
					<th></th>
				</tr>
				</thead>
				<tbody>
				<?php if ($this->GetAgendaInformation): ?>
					<?php foreach ($this->GetAgendaInformation as $key => $val): ?>
						<tr>
							<td><?php echo $this->escape($val['nombre']) ?></td>
							<td><?php echo $this->escape($val['apellido']) ?></td>
							<td><?php echo $this->escape($val['direccion']) ?></td>
							<td><?php echo $this->escape($val['correo']) ?></td>
							<td><?php echo $this->escape($val['telefonos']) ?></td>
							<td>
								<button data-toggle="modal" data-target="#myModal" type="button" data-id="<?php echo $this->escape($val['id_contactos']) ?>"
										class="btn btn-primary editar" aria-label="Left Align">
									<span class="glyphicon glyphicon-pencil" aria-hidden="true" > </span>
								</button>
							</td>
						</tr>
					<?php endforeach; ?>
				<?php endif;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
	<div class="modal-dialog " role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Crear Nuevo Contacto</h4>
			</div>
			<div class="modal-body">
				<form id="validacion_test">
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label for="email">Nombre:</label>
								<input type="text" class="form-control nombre required" name="nombre">
								<input type="hidden" class="id" name="id">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label for="pwd">Apellido:</label>
								<input type="text" class="form-control apellido required" name="apellido">
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label for="pwd">Telefonos:</label>
								<select id="tags" name="tags[]" multiple="multiple" class="form-control required">
								</select>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label for="email">Correo:</label>
								<input type="email" class="form-control correo required" name="correo">
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label for="pwd">Dirección:</label>
								<textarea class="form-control direccion required" name="direccion" id="" cols="60" rows="4" style="margin-left: 0px; margin-right: -302px; width: 567px;"></textarea>
							</div>
						</div>
					</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
				<button type="submit" class="btn btn-primary saveInfo">Guardar</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</body>
</html>
</form>
<script>
	$( document ).ready(function() {
		ajaxurl= "<?php echo $this->url(array('controller' => 'Agend',
	'action' => 'insertar')); ?>";
		list= "<?php echo $this->url(array('controller' => 'Agend',
	'action' => 'list')); ?>";
		ajaxupdate= "<?php echo $this->url(array('controller' => 'Agend',
	'action' => 'update')); ?>";
		$('#myModal').on('shown.bs.modal', function(e) {
			$( ".saveInfo" ).prop( "disabled", false );
			$("#nombre-error, #apellido-error").remove();
			id_contactos = 0;
			thisButton = $(e.relatedTarget);
			$('#tags').val('').change();
			$('.nombre').val('');
			$('.apellido').val('');
			$('.direccion').val('');
			$('.correo').val('');
			$('.direccion').val('');
			// Evaluo si le dieron click aun boton de editar
			if (thisButton.hasClass('editar')) {
				// Guardo la data que tiene el boton editar
				id_contactos = thisButton.data('id');
				$.ajax({
					type: "POST",
					url:  list,
					data :  { id : id_contactos},
					dataType: "json",
					success: function (result) {
						ArrayResult = result;
						if(ArrayResult.length >= 1){
							$('#tags').val('').change();
							$('.nombre').val(ArrayResult[0].nombre);
							$('.apellido').val(ArrayResult[0].apellido);
							$('.direccion').val(ArrayResult[0].direccion);
							$('.correo').val(ArrayResult[0].correo);
							telefonos = ArrayResult[0].telefonos.split(',');
							$.each(telefonos, function( index, value ) {
								if(value != "")
									$option1 = $("<option selected></option>").val(value).text(value);
								$('#tags').append($option1).trigger('change');
							});
						}
					},
					error: function (request, status, error) {
						console.log('error de la petición Jquery');
					}
				});

			}

			$('.id').val(id_contactos);


			$('form').validate({

				rules:
				{
					correo: { required:true, email:true, minlength:8, maxlength:80},
					nombre: { required:true},
					apellido: { required:true},
					direccion: { required:true },
					tags: { required:true,  digits: true,  minlength:3, maxlength:15}
				},
				messages: {
					correo: {
						required: "Por favor ingrese el correo",
						email: "Correo invalido",
						minlength: "El correo no debe ser menor a 8 caracteres",
						maxlength: "El correo no debe ser mayor a 8o caracteres"
					},

					nombre: "Por favor ingrese el nombre",
					apellido: "Por favor ingrese el apellido",
					direccion: "Por favor ingrese el direccion",
					"tags[]": "Campo requerido."
				},
				submitHandler: function (form) { // for demo

					$( ".saveInfo" ).prop( "disabled", true );

					FormSerialize =  $("form").serialize();
					url = ajaxurl;
					if(id_contactos >= 1){
						url = ajaxupdate;
					}
					// event.preventDefault();
					$.ajax({
						type: "POST",
						url:  url,
						data : FormSerialize,
						dataType: "json",
						success: function (result) {
							ArrayResult = result;
							$('.table-render').empty();
							$('.table-render').append(ArrayResult.html);
							$('#myModal').modal('hide');
							console.log(result);


							$('table').DataTable({
								"language": {
									"sProcessing":    "Procesando...",
									"sLengthMenu":    "Mostrar _MENU_ registros",
									"sZeroRecords":   "No se encontraron resultados",
									"sEmptyTable":    "Ningún dato disponible en esta tabla",
									"sInfo":          "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
									"sInfoEmpty":     "Mostrando registros del 0 al 0 de un total de 0 registros",
									"sInfoFiltered":  "(filtrado de un total de _MAX_ registros)",
									"sInfoPostFix":   "",
									"sSearch":        "Buscar:",
									"sUrl":           "",
									"sInfoThousands":  ",",
									"sLoadingRecords": "Cargando...",
									"oPaginate": {
										"sFirst":    "Primero",
										"sLast":    "Último",
										"sNext":    "Siguiente",
										"sPrevious": "Anterior"
									},
									"oAria": {
										"sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
										"sSortDescending": ": Activar para ordenar la columna de manera descendente"
									}
								}
							});
						},
						error: function (request, status, error) {
							console.log('error de la petición Jquery');
						}
					});
					return false;
				}
			});

			$.validator.setDefaults({
				highlight: function(element) {
					$(element).closest('.form-group').addClass('has-error');
				},
				unhighlight: function(element) {
					$(element).closest('.form-group').removeClass('has-error');
				},
				errorElement: 'span',
				errorClass: 'help-block',
				errorPlacement: function(error, element) {
					if(element.parent('.input-group').length) {
						error.insertAfter(element.parent());
					} else {
						error.insertAfter(element);
					}
				}
			});

			$('#tags').select2({
				tags: true
			});


		});
		//Spanish
		$('table').DataTable({
			"language": {
				"sProcessing":    "Procesando...",
				"sLengthMenu":    "Mostrar _MENU_ registros",
				"sZeroRecords":   "No se encontraron resultados",
				"sEmptyTable":    "Ningún dato disponible en esta tabla",
				"sInfo":          "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
				"sInfoEmpty":     "Mostrando registros del 0 al 0 de un total de 0 registros",
				"sInfoFiltered":  "(filtrado de un total de _MAX_ registros)",
				"sInfoPostFix":   "",
				"sSearch":        "Buscar:",
				"sUrl":           "",
				"sInfoThousands":  ",",
				"sLoadingRecords": "Cargando...",
				"oPaginate": {
					"sFirst":    "Primero",
					"sLast":    "Último",
					"sNext":    "Siguiente",
					"sPrevious": "Anterior"
				},
				"oAria": {
					"sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
					"sSortDescending": ": Activar para ordenar la columna de manera descendente"
				}
			}
		});
	});
</script>

